/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.sql.*;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sinxdell
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        setVisible(true);
        JLabel imgLabel = new JLabel(new ImageIcon("C:\\Users\\sinxdell\\Pictures\\nibm.jpg"));
        setSize(930, 560);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLogin = new java.awt.Button();
        txtUsername = new java.awt.TextField();
        checkbox1 = new java.awt.Checkbox();
        button2 = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(920, 560));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Password ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 290, 90, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/medical.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-90, 70, 1020, 120);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Dont have an Account?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 250, 160, 40);

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Medical Sales System");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 10, 440, 70);

        btnLogin.setBackground(new java.awt.Color(51, 51, 255));
        btnLogin.setLabel("Log in");
        btnLogin.setName("btnLogin"); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(210, 400, 300, 40);

        txtUsername.setName("txtUsername"); // NOI18N
        getContentPane().add(txtUsername);
        txtUsername.setBounds(320, 270, 180, 30);

        checkbox1.setBackground(new java.awt.Color(255, 255, 255));
        checkbox1.setLabel("Remember username");
        checkbox1.setName("chbRem"); // NOI18N
        getContentPane().add(checkbox1);
        checkbox1.setBounds(210, 360, 141, 20);

        button2.setBackground(new java.awt.Color(51, 51, 255));
        button2.setLabel("Register");
        button2.setName("btnRegister"); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(580, 290, 300, 40);

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Username ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 250, 90, 60);

        txtPwd.setBackground(new java.awt.Color(255, 255, 255));
        txtPwd.setForeground(new java.awt.Color(0, 0, 0));
        txtPwd.setName("txtPwd"); // NOI18N
        getContentPane().add(txtPwd);
        txtPwd.setBounds(320, 312, 180, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/—Pngtree—blue gradient watercolor wild poster_978316.jpg"))); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 920, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        this.hide();
        RegisterScreen rs = new RegisterScreen();
        rs.show();
    }//GEN-LAST:event_button2ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            String databaseUsername = txtUsername.getText();
            String databasePassword = txtPwd.getText();
            Connection con = null;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/medical_sales", "root", "");
//          Statement stmt =  con.createStatement();
//            String sqlQ = "SELECT * FROM student WHERE student_index='" + txtUsername.getText() + "' && pwd='" + txtPwd.getText()+ "'";
//                 ResultSet rs = stmt.executeQuery(sqlQ);

            PreparedStatement st = (PreparedStatement) con.prepareStatement("Select email,pwd from login where email=? and pwd=?");
            st.setString(1, databaseUsername);
            st.setString(2, databasePassword);
            ResultSet rs = st.executeQuery();
            // Check Username and Password
//    while (rs.next()) {
//        databaseUsername = rs.getString("student_index");
//        databasePassword = rs.getString("pwd");
//    }
            if (rs.next()) {
                dispose();
                
                JOptionPane.showMessageDialog(null, "You have successfully logged in");
                  this.hide();
             Dashboard ds = new Dashboard(); 
             ds.show();
            } else {
                JOptionPane.showMessageDialog(null, "Wrong Username & Password");
            }

//    if (txtUsername.equals(databaseUsername) && txtPwd.equals(databasePassword)) {
//        System.out.println("Successful Login!\n----");
       
//    } else {
//        System.out.println("Incorrect Password\n----");
//        JOptionPane.showMessageDialog(null, "Password Incorrect.");
//    }
//            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Database not connected.");
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnLogin;
    private java.awt.Button button2;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtPwd;
    private java.awt.TextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
